### ISSUE TITLE
auto-create review tasks for legacy imports

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo-kenyalaw#10]
@longhotsummer is this what you had in mind?

Once a legacy import is completed on KL, create a task with a link to that import task 
(which will have links to all the successfully imported points in time and/or error messages).

The review task will be to sanity check the successful imports and resolve any issues/errors.

Anything else?

**Comment by longhotsummer** [comment]
Basically, yes, with a focus on checking the imported point in time for issues. So it may be more about the imported point in time (one task for each point in time), than the legacy import task itself.
